
server:
  port: 7080
spring:

  application:
    name: smart-bike
    version: 1
    description: Anonymous confession and advice platform backend
    base-url: http://localhost:9080

  mail:
    host: smtp.gmail.com
    port: 587
    username: biruksolomonmoges@gmail.com
    password: kbemdrrbdmkjxden
    from: noreply@smartbike.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    url: jdbc:postgresql://ep-summer-salad-aqlm9g8k-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_X4iqTO5aQkFj
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      password: admin123

# Default Admin Credentials (CHANGE IN PRODUCTION!)
admin:
  email: admin@smartbike.com
  password: Admin@123
  name: System Administrator
  phone: "+1234567890"

mqtt:
  broker: ssl://graycuckoo-7d8fe22a.a03.euc1.aws.hivemq.cloud:8883
  client-id: spring-backend

  username: hivemq.webclient.1778502183752
  password: Q0V9xay,E#DM>hF:g18l

jwt:
  secret: mySecretKeyForSmartBikeRentalApplicationWithMinimum256BitsLength
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    syntax-highlight:
      theme: monokai
    doc-expansion: list
    use-root-path: false
  packages-to-scan: com.IoT.smart_bike_rental_backend.controller
  paths-to-match: /**
  show-actuator: false


logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
            access:
              intercept:
                FilterSecurityInterceptor: DEBUG
    com:
      IoT:
        smart_bike_rental_backend:
          controller:
            AuthController: DEBUG
