
server:
  port: 7080
spring:

  application:
    name: smart-bike
    version: 1
    description: Anonymous confession and advice platform backend
    base-url: http://localhost:9080

  mail:
    host: smtp.gmail.com
    port: 587
    username: biruksolomonmoges@gmail.com
    password: kbemdrrbdmkjxden
    from: noreply@smartbike.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    url: jdbc:mysql://localhost:3306/smartbike?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 837535Abc@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: admin123

mqtt:
  broker: tcp://localhost:1883
  client-id: spring-backend

jwt:
  secret: mySecretKeyForSmartBikeRentalApplicationWithMinimum256BitsLength
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    syntax-highlight:
      theme: monokai
    doc-expansion: list
    use-root-path: false
  packages-to-scan: com.IoT.smart_bike_rental_backend.controller
  paths-to-match: /**
  show-actuator: false


logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
            access:
              intercept:
                FilterSecurityInterceptor: DEBUG
    com:
      IoT:
        smart_bike_rental_backend:
          controller:
            AuthController: DEBUG
