server:
  port: ${PORT:9080}

spring:
  application:
    name: smart-bike
    version: 1
    description: WiFi-based Smart Bike Rental Backend
    base-url: http://app:9080

  datasource:
    url: jdbc:postgresql://ep-summer-salad-aqlm9g8k-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_X4iqTO5aQkFj
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    from: ${SPRING_MAIL_FROM:noreply@smartbike.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    user:
      name: admin
      password: admin123

admin:
  email: ${ADMIN_EMAIL:admin@smartbike.com}
  password: ${ADMIN_PASSWORD:Admin@123}
  name: ${ADMIN_NAME:System Administrator}
  phone: ${ADMIN_PHONE:+1234567890}

mqtt:
  broker: ssl://graycuckoo-7d8fe22a.a03.euc1.aws.hivemq.cloud:8883
  client-id: spring-backend

  username: hivemq.webclient.1778502183752
  password: Q0V9xay,E#DM>hF:g18l
  connection:
    timeout: 30
    keepalive: 60
  reconnect:
    enabled: true
    delay: 5000

jwt:
  secret: ${JWT_SECRET:mySecretKeyForSmartBikeRentalApplicationWithMinimum256BitsLength}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    doc-expansion: list
  packages-to-scan: com.IoT.smart_bike_rental_backend.controller
  paths-to-match: /**
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com:
      IoT:
        smart_bike_rental_backend: DEBUG
  file:
    name: /app/logs/application.log
    max-size: 10MB
    max-history: 10
